### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by andrea-halloran** [rural-jurors/cheap-drugs#32]

**Comment by andrea-halloran** [comment]
@antoniojgage we are trying to deploy to Heroku. We have the step-by-step walk through for deploying with MySQL, and were wondering if we would follow the same steps if we used Sequelize. So far, we just ran Heroku Create and added JAWS DB as an add on. 

We found this documentation for hosting to Heroku with a Sequelize database, but did not know if it covered the correct steps: https://sequelize.readthedocs.io/en/1.7.0/articles/heroku/.  

Here is the link for deploying with MySQL: https://github.com/the-Coding-Boot-Camp-at-UT/UTAUS201807FSF4/blob/master/01-Class-Content/14-handlebars/03-Supplemental/MySQLHerokuDeploymentProcess.pdf. 

Thanks!

**Comment by Andrea** [comment]
HI, I am @andrea (not part of your project)  please correct handle :D thanks

> The instructions vary. You’re close but your config file is off. Invite me to the heroku app as a collaborator. Your config should look like this for production. @Andrea
>
